# Generated by Django 4.1.5 on 2023-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_tag_remove_product_image_product_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tag',
            field=models.ManyToManyField(to='core.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
